# Generated by Django 4.2 on 2023-04-15 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='films.category'),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
    ]
