# Generated by Django 4.2 on 2023-04-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_tag_remove_film_image_image_film_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.CharField(choices=[('comedy', 'Комедия'), ('drama', 'Драма'), ('horror', 'Ужасы')], default=1),
            preserve_default=False,
        ),
    ]
